image: ruby:3.1

pipelines:
  pull-requests:
    "**":
      - step:
          name: PR Agent Review
          image: python:3.10
          services:
            - docker
          script:
            - docker run -e CONFIG.GIT_PROVIDER=bitbucket -e OPENAI.KEY=sk-gpwoq4KZqxCbH1fqDPElT3BlbkFJUgDqimiU0A9Gh9EwBSxoa -e BITBUCKET.BEARER_TOKEN=$CodiumToken codiumai/pr-agent:latest --pr_url=https://bitbucket.org/$BITBUCKET_WORKSPACE/$BITBUCKET_REPO_SLUG/pull-requests/$BITBUCKET_PR_ID review

  branches:
    "{GALE-*, develop}":
      - step:
          name: Build Jekyll site
          script:
            - echo "We are good to go, build Jekyll site"
    develop:
      - step:
          name: Raise PR to main
          script:
            - echo "We are good to go, raise PR to main"
    main:
      - step:
          name: Build and Deploy to Production
          deployment: Production
          trigger: manual
          clone:
            enabled: false
          script:
            - echo "We are good to go, build and deploy Jekyll site to production"
definitions:
  caches:
    bundler: ~/.bundle
    node: ~/.npm
